{
	"version": 1542409475,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/barraloader.png",
		"images/mascara.png",
		"images/faixas-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/tdestinoef1intro.png",
		"images/negmef1intro-sheet0.png",
		"images/posmef1intro-sheet0.png",
		"images/velhinhoerrof1intro-sheet0.png",
		"images/tiledbackground8.png",
		"images/vetorescentimetros-sheet0.png",
		"images/ihudopcoesf2-sheet0.png",
		"images/ihudpausef2-sheet0.png",
		"images/breiniciarf2-sheet0.png",
		"images/tiledbackgroundf2.png",
		"images/bfecharf2-sheet0.png",
		"images/objetocriadof2-sheet0.png",
		"images/fundojogof2.png",
		"images/bgprogressovidaganha.png",
		"images/bolhinhasestouradasf2.png",
		"images/fundoprogressotempof2-sheet0.png",
		"images/divisaohudjogof2-sheet0.png",
		"images/bgprogressof2.png",
		"images/botpausajogof2-sheet0.png",
		"images/voltaaojogo-sheet0.png",
		"images/negm-sheet0.png",
		"images/voltaaojogo2f2-sheet0.png",
		"media/som bolha estourando.m4a",
		"media/som bolha estourando.ogg",
		"media/somjoguinhodabolha.ogg",
		"media/som drag botão.m4a",
		"media/som drag botão.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}